import os
from pathlib import Path

import argparse


import full_morph
import head_morph
import face_morph

parser = argparse.ArgumentParser(description="Script to generate morphed images")
parser.add_argument("--src",  required=True,
  help="Source image with the subject"
)
parser.add_argument("--dst",  required=True,
  help="Target image to receive the subject"
)
parser.add_argument("--out",  required=True,
  help="Output directory of the morphed images"
)
parser.add_argument("--frames",  required=True,
  help="Directory with the frames generated by facemorph"
)
parser.add_argument("--morph", required=True,
  choices=["full", "head", "face"],
  help="Type of morph to apply"
)
parser.add_argument("--correction", default=-0.035, type=float,
  help="Manual correction to the resize ratio of the face frame in facemorphing, when pasting to the original"
)
parser.add_argument("--iterations", default=100, type=int,
  help="Amunt of steps to morph between the source and destination"
)


# python morpher.py --src full_img/source_image-0.jpg --dst full_img/destination_image-0.jpg --out here --frames frames --morph face --iterations 10
def main():
  args = vars(parser.parse_args())
  os.makedirs(args["out"], exist_ok=True)
  # iterations = int(args["iterations"])
  
  out_dir = args["out"]
  if out_dir[-1] != "/":
    out_dir += "/"

  frames_dir = args["frames"]
  if frames_dir[-1] != "/":
    frames_dir += "/"

  if args["morph"] == "full":
    full_morph.fullmorph(args["src"], args["dst"], out_dir, args["iterations"])

  if args["morph"] == "head":
    head_morph.headmorph(args["src"], args["dst"], out_dir, args["iterations"])

  if args["morph"] == "face":
    face_morph.facemorph(args["src"], args["dst"], out_dir, frames_dir, args["iterations"], args["correction"])

if __name__ == "__main__":
  main()